### ISSUE TITLE
repository is likely to cause confusion

### ISSUE THREAD

**Issue by aspiers** [openSUSE/git-packaging-tools#1]
There is already an [`openSUSE/pack-tools`](https://github.com/openSUSE/pack-tools) repository here on GitHub.  I think that creating this new one is going to cause confusion, unless the scope of both repos  is clarified.  (Well, in fact it already did, since I'm not sure whether the scope of the old repo includes this project or not ;-)

Kudos to @isbm for writing a very nice README for this repo, and no kudos to anyone for writing a README in the other repo, since it doesn't exist ;-)  But IMHO it's usually good netizenship to check for prior art before creating a new project, and helping prospective users understand how the new project is different from the old one, and what the pros/cons of the new project are.

So I would suggest that we:

- [x] Figure out what the scope of the other repo is
- [ ] Add a README to the other repo
- [ ] Extend both repos' READMEs to explain the differences between them.

**Comment by isbm** [comment]
The scope of this repo is to manage patches, that are tracked by Git. We are supporting Salt package that way, but I thought it would be useful to others, who wants Git **and** patches (non-patch Git-only story I got, but this is not for us).

**Comment by lnussel** [comment]
[ ] limit the amount of people who can create repos in the openSUSE organization to prevent everyone and their dog to put stuff there.

**Comment by isbm** [comment]
I don't see this as a constructive discussion, sorry. Therefore closing.
P.S. @lnussel and, wow, it was rude!

**Comment by lnussel** [comment]
sorry to step on your toes here and that it hit you here. Nevertheless as a matter of fact I see new repos appearing every week without anyone trying to coordinate that somehow. So the discussion needs to happen somehow.

**Comment by isbm** [comment]
This is not the place for such discussion. Thanks.

**Comment by aspiers** [comment]
@isbm What was not constructive about my original issue report?

**Comment by isbm** [comment]
@aspiers not your. I don't want to turn this place into a trash can for irrelevant rants. What the scope of this repo is pretty clear: help to those, who is using scenario where package maintenance requires numerous patches, that are tracked in the Git repo. Not sure why we need to cross-link repos, but we can cross-mention "related projects", I am fine.

Feel free to PR here.
