### ISSUE TITLE
architectural discussion

### ISSUE THREAD

**Issue by aspiers** [openSUSE/git-packaging-tools#2]
(Sorry for filing an issue for something which isn't a specific bug or feature request, but I'm not sure if there was a better place to start this discussion.  Maybe [the `opensuse-packaging@opensuse.org` mailing list](https://lists.opensuse.org/opensuse-packaging/) is - I'm happy to repost there if you prefer.)

I wanted to point out that I already built [a toolchain which does something extremely similar](https://github.com/openSUSE/pack-tools/tree/master/contrib/BS-pkg-testing).  The primary difference is that it doesn't bother using patches at all, but takes the source directly from a git branch.  This eliminates all the headaches around patches which your project addresses.  Since your README states that you are keen to avoid living in the stone or bronze ages (and BTW I couldn't agree more that this is a good idea ;-), I'm puzzled why you decided to carry on working with patches, when AFAICS `git` accomplishes all the necessary patch management already.  Perhaps you could clarify the reasons for this decision?

There are some key points regarding the "ditch all the patches and use git" approach which you probably need to know:

- We've been using this in the SUSE OpenStack Cloud team for almost 5 years, and it works very nicely for us.
- We use [`tar_scm`](https://github.com/openSUSE/obs-service-tar_scm/) to build the tarball directly from whichever `git` repo / branch we choose.
- The tarball, and hence the package version number, includes the timestamp (in UNIX epoch format) of the commit at the branch's head.  This guarantees that as much as possible, versions are monotonically increasing over time.  Of course if you rewrite git history with `push -f` then that guarantee is lost, but if you do that, then you have to deal with the consequences regardless of which packaging strategy you use.
- The tarball, and hence the package version number, also includes the abbreviated SHA1 of the commit at the head of the branch, so you can always deterministically map a package version back to the *exact* sources which were used to build it.  IMHO that is quite a big advantage over the patch-based approach, where IIUC you can only do that if you have the corresponding source rpm.  (Or is there some implicit contract where `git-format-pkg-patch` guarantees that the sources built from the generated patches are bitwise identical to an existing `git` commit?  If so, I'm wrong about the advantage, but I got the impression there was no such guarantee.)
- A follow-on advantage of the above is that you can use the full `git` ecosystem for comparing those sources with other branches / tags / package versions / working trees.
- `tar_scm` can automatically update the `.changes` file.
- Here's [an example `_service` file](https://build.opensuse.org/package/view_file/systemsmanagement:crowbar:4.0/crowbar-core/_service?expand=1).
- It is of course possible to break the contract mentioned above, by adding one or two patches to be applied on top of the `git` branch.  Sometimes this might make sense, e.g. a branding patch which does not belong in the upstream repo, or a contentious PR which hasn't been merged yet.  But the more patches are added, the further the sources drift from the exact tree described by the SHA1, so personally I prefer to avoid this.

I'm sure there are some disadvantages to our approach too.  Please let me know your thoughts!

**Comment by isbm** [comment]
@aspiers We know about service and we tried that before. However this is not what we are doing today. We are ought to take an official source from official release tag as a tarball with an exact checksum and then therefore put patches on top if it that we think has to apply. And yes, we do force-push. :-)

**Comment by aspiers** [comment]
Well then it's worth documenting that use case in order to address #1.
